#!/bin/sh
set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <workspace_dir>" >&2
    exit 1
fi

overlay_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
workspace_dir=$1
tcc27_dir=$workspace_dir/tcc_27
loader=${TCC23_ALT_LOADER:-../x86/bin/elf_loader_cc_x86.exe}

cd "$tcc27_dir"
rm -f qsort_boot.o tcc_from23_direct.o libtcc1_from23_direct.o libtcc1_self1.o tcc_self1.o

$loader \
    -l ../tcc_23/libc_boot2.o -l ../tcc_23/libtcc1.o -l ../tcc_23/tcc.o \
    -c "$overlay_dir/phase1_support/qsort_boot.c" -o qsort_boot.o

$loader \
    -l ../tcc_23/libc_boot2.o -l ../tcc_23/libtcc1.o -l ../tcc_23/tcc.o \
    -I ../woody/usr/include/ -I include \
    -c tcc.c -DONE_SOURCE -o tcc_from23_direct.o

$loader \
    -l ../tcc_23/libc_boot2.o -l ../tcc_23/libtcc1.o -l ../tcc_23/tcc.o \
    -c ./lib/libtcc1.c -o libtcc1_from23_direct.o

$loader \
    -l qsort_boot.o -l ../tcc_23/libc_boot2.o -l libtcc1_from23_direct.o -l tcc_from23_direct.o \
    -c ./lib/libtcc1.c -o libtcc1_self1.o

$loader \
    -l qsort_boot.o -l ../tcc_23/libc_boot2.o -l libtcc1_from23_direct.o -l tcc_from23_direct.o \
    -I ../woody/usr/include/ -I include \
    -c tcc.c -DONE_SOURCE -o tcc_self1.o

$loader \
    -l qsort_boot.o -l ../tcc_23/libc_boot2.o -l libtcc1_self1.o -l tcc_self1.o \
    -c ./lib/libtcc1.c -o libtcc1.o

$loader \
    -l qsort_boot.o -l ../tcc_23/libc_boot2.o -l libtcc1_self1.o -l tcc_self1.o \
    -I ../woody/usr/include/ -I include \
    -c tcc.c -DONE_SOURCE -o tcc.o
