#!/bin/sh
set -eu

overlay_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
workspace_dir=$("$overlay_dir/mk_prepare_workspace_alt")
out_dir="$workspace_dir/host_debug"

mkdir -p "$out_dir"

(
    cd "$overlay_dir/tcc_3_alt"
    gcc -m32 -D__thread=__threadp tcc.c -I "$workspace_dir/woody/usr/include/" -ldl -o "$out_dir/tcc3_alt_host.exe"
)

echo "$out_dir/tcc3_alt_host.exe"
