#!/bin/sh
set -eu

overlay_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root="$overlay_dir/.."
workspace_dir=$("$overlay_dir/mk_prepare_workspace_alt")

(
    cd "$workspace_dir/tcc_3"
    gcc -m32 -D__thread=__threadp tcc.c -I ../woody/usr/include/ -ldl -o a.out
)

(
    cd "$repo_root"
    ./scripts/run-i386.sh /bin/sh -c "cd '$workspace_dir/tcc_23' && rm -f libtcc1.o tcc.o a.out && ../tcc_3/a.out tcc.c -c libtcc1.c && ../tcc_3/a.out tcc.c -I ../woody/usr/include/ -I . -c tcc.c"
)

(
    cd "$workspace_dir/tcc_23"
    gcc -m32 libtcc1.o tcc.o -ldl -o a.out
)

(
    cd "$repo_root"
    ./scripts/run-i386.sh /bin/sh -c "cd '$workspace_dir/tcc_23' && ./a.out -h"
)
