#!/bin/sh

# Run from tcc_27_layered_take3. SpiderMonkey is the only compiler seed.
set -eu
cd ..
mkdir -p artifacts
cd artifacts

js ../tcc_27_layered_take3/tests/layered/cc1_js_bootstrap.js
mv -f cc1_js.o cc1.o
mv -f cc2_stubs_js.o cc2_stubs.o
mv -f cc1_js.exe cc1.exe
mv -f cc1_static_js.exe cc1_static.exe
chmod +x cc1.exe cc1_static.exe
