#!/bin/sh
set -eu

./mk_loader
./artifacts/otccelf_js.exe elf_loader.c artifacts/elf_loader_otcc.exe
chmod +x artifacts/elf_loader_otcc.exe

cd ../tcc_23/
rm -f ./*.o

../otccelf/artifacts/elf_loader_otcc.exe -l ../tcc_10/tcc.o -o tcc.o -c tcc.c
../otccelf/artifacts/elf_loader_otcc.exe -l ../tcc_10/tcc.o -o libtcc1_min.o -c libtcc1_min.c

../otccelf/artifacts/elf_loader_otcc.exe -l libtcc1_min.o -l tcc.o -c libtcc1.c
../otccelf/artifacts/elf_loader_otcc.exe -l libtcc1_min.o -l tcc.o -I ../woody/usr/include/ -I . -c tcc.c
